In [1]:
#This code is for adaptive GPU usage
import keras.backend as K
cfg = K.tf.ConfigProto()
cfg.gpu_options.allow_growth = True
K.set_session(K.tf.Session(config=cfg))

Using TensorFlow backend.

In [2]:
!pip3 install rouge

Requirement already satisfied: rouge in /opt/anaconda/lib/python3.6/site-packages (0.3.1)

In [2]:
import os
import tensorflow as tf
import pandas as pd
import numpy as np
import zipfile
from __future__ import division
import nltk
from nltk.corpus import wordnet as wn
from nltk.corpus import brown
import math
import numpy as np
import sys
import tarfile
import json

In [ ]:
# tar = tarfile.open("processed_data.tar.gz", "r:gz")
# tar.extractall()
# tar.close()

In [ ]:
#data = pd.read_csv(tar.open("processed_1"),delimiter='\t',header=None)

In [6]:
data = pd.read_csv('fully_processed_data.csv')
data.head()

,primary_id,queryID,query,response,label,labelID,q_word_count,q_char_count,q_avg_word,q_stopwords,q_numerics,r_word_count,r_char_count,r_avg_word,r_stopwords,r_numerics,q_polarity,q_subjectivity,r_polarity,r_subjectivity
0,361570.0,361570,lewisia,plant number lewisia native western north amer...,0,0,3,15,4.333333,2,0,95,592,5.242105,24,0,0.0,0.0,0.02295,0.363492
1,361570.1,361570,lewisia,alphabetical list perennial lewisia native wes...,0,1,3,15,4.333333,2,0,99,616,5.232323,26,0,0.0,0.0,0.02295,0.363492
2,361570.2,361570,lewisia,lewisia plant genus named meriwether lewis enc...,1,2,3,15,4.333333,2,0,76,461,5.078947,31,1,0.0,0.0,0.05000,0.066667
3,361570.3,361570,lewisia,alphabetical list perennial lewisia native wes...,0,3,3,15,4.333333,2,0,108,705,5.537037,26,0,0.0,0.0,0.16754,0.466190
4,361570.4,361570,lewisia,lewisia related specie best known lewisia undo...,0,4,3,15,4.333333,2,0,118,746,5.330508,41,0,0.0,0.0,0.07004,0.375595

In [4]:
tdata = pd.read_csv('Full_Rogue_Data_Latest.csv')
print(len(tdata))
tdata.head()

5186830

,queryID,query,response,label,labelID,rouge-1_f,rouge-1_p,rouge-1_r,rouge-2_f,rouge-2_p,rouge-2_r,rouge-l_f,rouge-l_p,rouge-l_r
0,318790,fixed asset annuity,fixed index annuity long-term retirement produ...,1,0,0.272727,0.157895,1.000000,0.0,0.0,0.0,0.107464,0.105263,0.666667
1,318790,fixed asset annuity,amount insurance company credit depends variet...,0,1,0.062500,0.034483,0.333333,0.0,0.0,0.0,0.034813,0.034483,0.333333
2,318790,fixed asset annuity,"fixed index annuity ? simply put , contract cl...",0,2,0.083333,0.044444,0.666667,0.0,0.0,0.0,0.044629,0.044444,0.666667
3,318790,fixed asset annuity,fixed indexed annuity . us unique formula calc...,0,3,0.129032,0.071429,0.666667,0.0,0.0,0.0,0.072160,0.071429,0.666667
4,318790,fixed asset annuity,"example , start $ 100,000 invested . 1 assumpt...",0,4,0.064516,0.035714,0.333333,0.0,0.0,0.0,0.036080,0.035714,0.333333

In [20]:
tdata['rouge-1_f'][20002]

1e-05

In [30]:
data = pd.read_csv("Tree_Model/Clean_data_latest_0.csv")
data.head()

,0,1,2,3,4
0,131,. corporation ?,"company incorporated specific nation , often w...",0,0
1,131,. corporation ?,"today , growing community 2,100 certified b co...",0,1
2,131,. corporation ?,"corporation definition , association individua...",0,2
3,131,. corporation ?,example corporation sentence . 1 work consulta...,0,3
4,131,. corporation ?,1 : government-owned corporation ( utility rai...,0,4

In [31]:
data.columns = ['queryID','query','response','label','labelID']

In [32]:
data.head()

,queryID,query,response,label,labelID
0,131,. corporation ?,"company incorporated specific nation , often w...",0,0
1,131,. corporation ?,"today , growing community 2,100 certified b co...",0,1
2,131,. corporation ?,"corporation definition , association individua...",0,2
3,131,. corporation ?,example corporation sentence . 1 work consulta...,0,3
4,131,. corporation ?,1 : government-owned corporation ( utility rai...,0,4

In [33]:
len(data)

5241830

In [21]:
exp = tdata.iloc[20000:].copy(deep = True)
from rouge import Rouge 
rouge = Rouge()
scores = rouge.get_scores("Hey you","Me")
for key, value in scores[0].items():
    for key1, value1 in value.items():
      #print (key1, value1)
      exp[(str)(key+"_"+key1)] = 0.00001

In [22]:
exp.head()

,queryID,query,response,label,labelID,rouge-1_f,rouge-1_p,rouge-1_r,rouge-2_f,rouge-2_p,rouge-2_r,rouge-l_f,rouge-l_p,rouge-l_r
20000,367465,nicotine salt,"nicotine 's high risk health , nicotine patch ...",0,0,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001
20001,367465,nicotine salt,nicotine form nicotine replacement product le ...,0,1,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001
20002,367465,nicotine salt,primary therapeutic use nicotine treating nico...,0,2,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001
20003,367465,nicotine salt,"however , found nicotine yield individual prod...",0,3,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001
20004,367465,nicotine salt,"tuesday , may 16 , 2017 11:40:04 america/los_a...",0,4,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001

In [24]:

#exp = data.copy(deep = True)
# exp['recall'] = 0.0001
# exp['precision'] = 0.0001
#     exp['recall'][i] = (len(  set(exp['query'][i].split()).intersection( set(exp['response'][i].split()) ) ))/(len(exp['query'][i].split()))
#     exp['precision'][i] = (len(  set(exp['query'][i].split()).intersection( set(exp['response'][i].split()) ) ))/(len(exp['response'][i].split()))
for i in exp.index:
    scores = rouge.get_scores(exp['response'][i],exp['query'][i])
    for key, value in scores[0].items():
        for key1, value1 in value.items():
          #print (key1, value1)
          exp[(str)(key+"_"+key1)][i] = value1
    if(i%25 == 0):
        print(i)
    if(i%100 == 0):
        exp.to_csv('Full_Rogue_Data_Latest_2.csv',index=False)

/mnt/home/divi/.local/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

20000
20025
20050
20075
20100
20125
20150
20175
20200
20225
20250
20275
20300
20325
20350
20375
20400
20425
20450
20475
20500
20525
20550
20575
20600
20625
20650
20675
20700
20725
20750
20775
20800
20825
20850
20875
20900
20925
20950
20975
21000
21025
21050
21075
21100
21125
21150
21175
21200
21225
21250
21275
21300
21325
21350
21375
21400
21425
21450
21475
21500
21525
21550
21575
21600
21625
21650
21675
21700
21725
21750
21775
21800
21825
21850
21875
21900
21925
21950
21975
22000
22025
22050
22075
22100
22125
22150
22175
22200
22225
22250
22275
22300
22325
22350
22375
22400
22425
22450
22475
22500
22525
22550
22575
22600
22625
22650
22675
22700
22725
22750
22775
22800
22825
22850
22875
22900
22925
22950
22975
23000
23025
23050
23075
23100
23125
23150
23175
23200
23225
23250
23275
23300
23325
23350
23375
23400
23425
23450
23475
23500
23525
23550
23575
23600
23625
23650
23675
23700

KeyboardInterrupt:

In [7]:
archive = zipfile.ZipFile('data.zip', 'r')
data = pd.read_csv(archive.open("data.tsv"),delimiter='\t',header=None)
data.columns = ['queryID','query','response','label','labelID']
data.isnull().values.any()

False

In [8]:
def basic_cleaning(df,column):
  #Split a-b into a and b
  df[column] = df[column].str.replace('-',' ')
  print(column+": - Replaced")
  #Replace all numbers
  #df[column] = df[column].str.replace('[0-9]+','')
  #print(column+": Numbers Replaced")
  #Convert to lowercase
  df[column] = df[column].apply(lambda x: " ".join(x.lower() for x in x.split()))
  print(column+": Converted to lowercase")
  #Remove punctuations
  df[column] = df[column].str.replace('[^\w\s]','')
  print(column+": Removed punctions ")
  return df[column]

In [9]:
data['query'] = basic_cleaning(data,'query')
data['response'] = basic_cleaning(data,'response')

query: - Replaced
response: Converted to lowercase
response: Removed punctions

In [10]:
data.head()

,queryID,query,response,label,labelID
0,131,what is a corporation,a company is incorporated in a specific nation...,0,0
1,131,what is a corporation,today there is a growing community of more tha...,0,1
2,131,what is a corporation,corporation definition an association of indiv...,0,2
3,131,what is a corporation,examples of corporation in a sentence 1 he wor...,0,3
4,131,what is a corporation,1 a government owned corporation as a utility ...,0,4

In [ ]:
!pip3 install allennlp

In [12]:
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-elmo-2018.02.19.tar.gz")

ModuleNotFoundError: No module named 'allennlp'

In [ ]:
exp = data.copy(deep=True)#pr.iloc[:100].copy(deep = True)
exp['Entailment'] = 1
exp['Contradiction'] = 1
exp['Neutral'] = 1
for i in exp.index:
  l = predictor.predict(hypothesis=exp['query'][i],premise=exp['response'][i])['label_probs']
  exp['Entailment'][i] = l[0]*100
  exp['Contradiction'][i] = l[1]*100
  exp['Neutral'][i] = l[2]*100
  if(i%25==0):
    print(i)
  if(i%100 == 0):
    exp.to_csv('Allen_Data.csv',index=False)

In [17]:
!pip3 install allennlp
from allennlp.commands.elmo import ElmoEmbedder
elmo = ElmoEmbedder()

Collecting allennlp
  Downloading https://files.pythonhosted.org/packages/92/87/905d0ac536477490ee3392f0db97f40fae7f0ec6baee52e44880a20a2515/allennlp-0.8.0-py3-none-any.whl (10.1MB)
    100% |████████████████████████████████| 10.1MB 320kB/s eta 0:00:01
Collecting sqlparse==0.2.4 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: cffi==1.11.5 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.11.5)
Collecting spacy<2.1,>=2.0 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/ae/6e/a89da6b5c83f8811e46e3a9270c1aed90e9b9ee6c60faf52b7239e5d3d69/spacy-2.0.18-cp36-cp36m-manylinux1_x86_64.whl
Collecting jsonnet==0.10.0; sys_platform != "win32" (from allennlp)
Requirement already satisfied: flask==1.0.2 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.0.2)
Requirement already satisfied: awscli>=1.11.91 in /opt/anaconda/lib/python3.6/site-packages/awscli-1.14.46-py3.6.egg (from allennlp) (1.14.46)
Collecting overrides (from allennlp)
Collecting pytz==2017.3 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/a3/7f/e7d1acbd433b929168a4fb4182a2ff3c33653717195a26c1de099ad1ef29/pytz-2017.3-py2.py3-none-any.whl
Requirement already satisfied: boto3 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.9.32)
Requirement already satisfied: gevent==1.3.6 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.3.6)
Requirement already satisfied: numpy in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.15.3)
Requirement already satisfied: tqdm>=4.19 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (4.19.5)
Requirement already satisfied: pytest in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (3.9.3)
Collecting editdistance (from allennlp)
  Using cached https://files.pythonhosted.org/packages/dc/34/381c67595831fc9daa30c9247cfb8116941fc7380b571a390bbff6da011e/editdistance-0.5.2-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: scikit-learn in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (0.19.1)
Collecting conllu==0.11 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/d4/2c/856344d9b69baf5b374c395b4286626181a80f0c2b2f704914d18a1cea47/conllu-0.11-py2.py3-none-any.whl
Requirement already satisfied: msgpack<0.6.0,>=0.5.6 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (0.5.6)
Collecting parsimonious==0.8.0 (from allennlp)
Requirement already satisfied: requests>=2.18 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (2.20.0)
Collecting flask-cors==3.0.7 (from allennlp)
  Downloading https://files.pythonhosted.org/packages/65/cb/683f71ff8daa3aea0a5cbb276074de39f9ab66d3fbb8ad5efb5bb83e90d2/Flask_Cors-3.0.7-py2.py3-none-any.whl
Collecting tensorboardX==1.2 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/c5/22/43f4f0318f7c68a1000dbb700a353b745584bc2397437832d15ba69ea5f1/tensorboardX-1.2-py2.py3-none-any.whl
Requirement already satisfied: h5py in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (2.8.0)
Collecting moto==1.3.4 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/ee/8f/7b36e81ff067d0e7bf90f7210b351c0cfe6657f79fa4dcb0cb4787462e05/moto-1.3.4-py2.py3-none-any.whl
Collecting ftfy (from allennlp)
Requirement already satisfied: nltk in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (3.2.5)
Collecting matplotlib==2.2.3 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/9e/59/f235ab21bbe7b7c6570c4abf17ffb893071f4fa3b9cf557b09b60359ad9a/matplotlib-2.2.3-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: scipy in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.1.0)
Requirement already satisfied: unidecode in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.0.23)
Requirement already satisfied: torch>=0.4.1 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (1.0.0)
Requirement already satisfied: flaky in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (3.4.0)
Requirement already satisfied: numpydoc==0.8.0 in /opt/anaconda/lib/python3.6/site-packages (from allennlp) (0.8.0)
Collecting pytorch-pretrained-bert==0.3.0 (from allennlp)
  Downloading https://files.pythonhosted.org/packages/26/85/de4dd7e018a197280752881adf7b4142886f20155145f641f7c803c0018a/pytorch_pretrained_bert-0.3.0-py3-none-any.whl
Collecting responses>=0.7 (from allennlp)
  Using cached https://files.pythonhosted.org/packages/2f/d8/a77cbd4cb8366ad0e275f2c642b50b401da22a2f5714e003e499fddca106/responses-0.10.5-py2.py3-none-any.whl
Requirement already satisfied: pycparser in /opt/anaconda/lib/python3.6/site-packages (from cffi==1.11.5->allennlp) (2.19)
Collecting cymem<2.1.0,>=2.0.2 (from spacy<2.1,>=2.0->allennlp)
  Using cached https://files.pythonhosted.org/packages/3d/61/9b0520c28eb199a4b1ca667d96dd625bba003c14c75230195f9691975f85/cymem-2.0.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy<2.1,>=2.0->allennlp)
  Using cached https://files.pythonhosted.org/packages/38/40/6b39438f7eefbb46460f645b8eefebc0c5f1cd38a934a2189c39d8bd0225/murmurhash-1.0.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting preshed<2.1.0,>=2.0.1 (from spacy<2.1,>=2.0->allennlp)
  Using cached https://files.pythonhosted.org/packages/20/93/f222fb957764a283203525ef20e62008675fd0a14ffff8cc1b1490147c63/preshed-2.0.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting ujson>=1.35 (from spacy<2.1,>=2.0->allennlp)
Collecting plac<1.0.0,>=0.9.6 (from spacy<2.1,>=2.0->allennlp)
  Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
Requirement already satisfied: dill<0.3,>=0.2 in /opt/anaconda/lib/python3.6/site-packages (from spacy<2.1,>=2.0->allennlp) (0.2.7.1)
Collecting thinc<6.13.0,>=6.12.1 (from spacy<2.1,>=2.0->allennlp)
  Using cached https://files.pythonhosted.org/packages/db/a7/46640a46fd707aeb204aa4257a70974b6a22a0204ba703164d803215776f/thinc-6.12.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting regex==2018.01.10 (from spacy<2.1,>=2.0->allennlp)
Requirement already satisfied: Werkzeug>=0.14 in /opt/anaconda/lib/python3.6/site-packages (from flask==1.0.2->allennlp) (0.14.1)
Requirement already satisfied: Jinja2>=2.10 in /opt/anaconda/lib/python3.6/site-packages (from flask==1.0.2->allennlp) (2.10)
Requirement already satisfied: itsdangerous>=0.24 in /opt/anaconda/lib/python3.6/site-packages (from flask==1.0.2->allennlp) (1.1.0)
Requirement already satisfied: click>=5.1 in /opt/anaconda/lib/python3.6/site-packages (from flask==1.0.2->allennlp) (7.0)
Collecting PyYAML<=3.12,>=3.10 (from awscli>=1.11.91->allennlp)
Collecting botocore==1.8.50 (from awscli>=1.11.91->allennlp)
  Downloading https://files.pythonhosted.org/packages/5a/9f/c74178afb86983446a4aea1f308272f6e92a96dd7b6efd086eb50241b10c/botocore-1.8.50-py2.py3-none-any.whl (4.1MB)
    100% |████████████████████████████████| 4.1MB 4.9MB/s ta 0:00:011
Collecting colorama<=0.3.7,>=0.2.5 (from awscli>=1.11.91->allennlp)
  Using cached https://files.pythonhosted.org/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl
Requirement already satisfied: docutils>=0.10 in /opt/anaconda/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp) (0.14)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli>=1.11.91->allennlp)
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Requirement already satisfied: s3transfer<0.2.0,>=0.1.12 in /opt/anaconda/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp) (0.1.13)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/anaconda/lib/python3.6/site-packages (from boto3->allennlp) (0.9.3)
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython" (from gevent==1.3.6->allennlp)
  Using cached https://files.pythonhosted.org/packages/bf/45/142141aa47e01a5779f0fa5a53b81f8379ce8f2b1cd13df7d2f1d751ae42/greenlet-0.4.15-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: py>=1.5.0 in /opt/anaconda/lib/python3.6/site-packages (from pytest->allennlp) (1.7.0)
Requirement already satisfied: six>=1.10.0 in /opt/anaconda/lib/python3.6/site-packages (from pytest->allennlp) (1.11.0)
Requirement already satisfied: setuptools in /mnt/home/divi/.local/lib/python3.6/site-packages (from pytest->allennlp) (38.5.1)
Requirement already satisfied: attrs>=17.4.0 in /opt/anaconda/lib/python3.6/site-packages (from pytest->allennlp) (18.2.0)

Requirement already satisfied: more-itertools>=4.0.0 in /opt/anaconda/lib/python3.6/site-packages (from pytest->allennlp) (4.3.0)
Requirement already satisfied: atomicwrites>=1.0 in /opt/anaconda/lib/python3.6/site-packages (from pytest->allennlp) (1.2.1)
Requirement already satisfied: pluggy>=0.7 in /opt/anaconda/lib/python3.6/site-packages (from pytest->allennlp) (0.8.0)
Requirement already satisfied: idna<2.8,>=2.5 in /opt/anaconda/lib/python3.6/site-packages (from requests>=2.18->allennlp) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda/lib/python3.6/site-packages (from requests>=2.18->allennlp) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/anaconda/lib/python3.6/site-packages (from requests>=2.18->allennlp) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/anaconda/lib/python3.6/site-packages (from requests>=2.18->allennlp) (3.0.4)
Requirement already satisfied: protobuf>=0.3.2 in /opt/anaconda/lib/python3.6/site-packages (from tensorboardX==1.2->allennlp) (3.6.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/anaconda/lib/python3.6/site-packages (from moto==1.3.4->allennlp) (2.7.4)
Collecting docker>=2.5.1 (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/e1/58/938fbc7acd98302ca4872f5eab8ab811498e342ab5aec0c1609f22e0aeda/docker-3.6.0-py2.py3-none-any.whl
Collecting xmltodict (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/42/a9/7e99652c6bc619d19d58cdd8c47560730eb5825d43a7e25db2e1d776ceb7/xmltodict-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: cryptography>=2.0.0 in /opt/anaconda/lib/python3.6/site-packages (from moto==1.3.4->allennlp) (2.3.1)
Collecting pyaml (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/c5/e1/1523fb1dab744e2c6b1f02446f2139a78726c18c062a8ddd53875abb20f8/pyaml-18.11.0-py2.py3-none-any.whl
Collecting mock (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: boto>=2.36.0 in /opt/anaconda/lib/python3.6/site-packages (from moto==1.3.4->allennlp) (2.49.0)
Collecting jsondiff==1.1.1 (from moto==1.3.4->allennlp)
Collecting aws-xray-sdk<0.96,>=0.93 (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/a4/a5/da7887285564f9e0ae5cd25a453cca36e2cd43d8ccc9effde260b4d80904/aws_xray_sdk-0.95-py2.py3-none-any.whl
Collecting cookies (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/6a/60/557f84aa2db629e5124aa05408b975b1b5d0e1cec16cde0bfa06aae097d3/cookies-2.2.1-py2.py3-none-any.whl
Collecting python-jose<3.0.0 (from moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/bf/5c/5fa238c0c5b0656994b52721dd8b1d7bf52ebd8786518dde794f44de86b6/python_jose-2.0.2-py2.py3-none-any.whl
Requirement already satisfied: wcwidth in /opt/anaconda/lib/python3.6/site-packages (from ftfy->allennlp) (0.1.7)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/anaconda/lib/python3.6/site-packages (from matplotlib==2.2.3->allennlp) (2.2.2)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda/lib/python3.6/site-packages (from matplotlib==2.2.3->allennlp) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda/lib/python3.6/site-packages (from matplotlib==2.2.3->allennlp) (1.0.1)
Requirement already satisfied: sphinx>=1.2.3 in /opt/anaconda/lib/python3.6/site-packages (from numpydoc==0.8.0->allennlp) (1.8.1)
Collecting msgpack-numpy<0.4.4 (from thinc<6.13.0,>=6.12.1->spacy<2.1,>=2.0->allennlp)
  Using cached https://files.pythonhosted.org/packages/ad/45/464be6da85b5ca893cfcbd5de3b31a6710f636ccb8521b17bd4110a08d94/msgpack_numpy-0.4.3.2-py2.py3-none-any.whl
Requirement already satisfied: wrapt<1.11.0,>=1.10.0 in /opt/anaconda/lib/python3.6/site-packages (from thinc<6.13.0,>=6.12.1->spacy<2.1,>=2.0->allennlp) (1.10.11)
Requirement already satisfied: cytoolz<0.10,>=0.9.0 in /opt/anaconda/lib/python3.6/site-packages (from thinc<6.13.0,>=6.12.1->spacy<2.1,>=2.0->allennlp) (0.9.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/anaconda/lib/python3.6/site-packages (from Jinja2>=2.10->flask==1.0.2->allennlp) (1.0)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda/lib/python3.6/site-packages (from rsa<=3.5.0,>=3.1.2->awscli>=1.11.91->allennlp) (0.4.2)
Collecting websocket-client>=0.32.0 (from docker>=2.5.1->moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/26/2d/f749a5c82f6192d77ed061a38e02001afcba55fe8477336d26a950ab17ce/websocket_client-0.54.0-py2.py3-none-any.whl
Collecting docker-pycreds>=0.3.0 (from docker>=2.5.1->moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: asn1crypto>=0.21.0 in /opt/anaconda/lib/python3.6/site-packages (from cryptography>=2.0.0->moto==1.3.4->allennlp) (0.24.0)
Collecting pbr>=0.11 (from mock->moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/f3/04/fddc1c2dd75b256eda4d360024692231a2c19a0c61ad7f4a162407c1ab58/pbr-5.1.1-py2.py3-none-any.whl
Collecting jsonpickle (from aws-xray-sdk<0.96,>=0.93->moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/ca/ce/97404d5aeb58e6155c216825c81b50f6eca8a5345c582317ae48391878f8/jsonpickle-1.0-py2.py3-none-any.whl
Collecting ecdsa<1.0 (from python-jose<3.0.0->moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/63/f4/73669d51825516ce8c43b816c0a6b64cd6eb71d08b99820c00792cb42222/ecdsa-0.13-py2.py3-none-any.whl
Collecting pycryptodome<4.0.0,>=3.3.1 (from python-jose<3.0.0->moto==1.3.4->allennlp)
  Using cached https://files.pythonhosted.org/packages/ab/bc/589fbae48c0969719f28b862d979f8e9d4d1e08bb7f68ad7a495b1ba2d54/pycryptodome-3.7.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting future<1.0 (from python-jose<3.0.0->moto==1.3.4->allennlp)
Requirement already satisfied: Pygments>=2.0 in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (2.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (1.2.1)
Requirement already satisfied: babel!=2.0,>=1.3 in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (2.6.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (0.7.12)
Requirement already satisfied: imagesize in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (1.1.0)
Requirement already satisfied: packaging in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (18.0)
Requirement already satisfied: sphinxcontrib-websupport in /opt/anaconda/lib/python3.6/site-packages (from sphinx>=1.2.3->numpydoc==0.8.0->allennlp) (1.1.0)
Requirement already satisfied: toolz>=0.8.0 in /opt/anaconda/lib/python3.6/site-packages (from cytoolz<0.10,>=0.9.0->thinc<6.13.0,>=6.12.1->spacy<2.1,>=2.0->allennlp) (0.9.0)
fastai 0.6 requires ipywidgets, which is not installed.
fastai 0.6 requires jupyter, which is not installed.
fastai 0.6 requires jupyter-console, which is not installed.
fastai 0.6 requires qtconsole, which is not installed.
fastai 0.6 requires widgetsnbextension, which is not installed.
plotnine 0.3.0 requires mizani>=0.4.1, which is not installed.
boto3 1.9.32 has requirement botocore<1.13.0,>=1.12.32, but you'll have botocore 1.8.50 which is incompatible.
moto 1.3.4 has requirement botocore>=1.9.16, but you'll have botocore 1.8.50 which is incompatible.
Installing collected packages: sqlparse, cymem, murmurhash, preshed, ujson, plac, msgpack-numpy, thinc, regex, spacy, jsonnet, overrides, pytz, editdistance, conllu, parsimonious, flask-cors, tensorboardX, websocket-client, docker-pycreds, docker, xmltodict, responses, PyYAML, pyaml, botocore, pbr, mock, jsondiff, jsonpickle, aws-xray-sdk, cookies, ecdsa, pycryptodome, future, python-jose, moto, ftfy, matplotlib, pytorch-pretrained-bert, allennlp, colorama, rsa, greenlet

  Found existing installation: pytz 2018.6
    Uninstalling pytz-2018.6:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/anaconda/lib/python3.6/site-packages/pytz-2018.6.dist-info/INSTALLER'
Consider using the `--user` option or check the permissions.

ModuleNotFoundError: No module named 'allennlp'

In [18]:
tdata = pd.read_csv("Rogue_Test_Data.csv")
tdata.head()

,Unnamed: 0,Unnamed: 0.1,queryID,query,response,labelID,q_word_count,q_char_count,q_avg_word,r_word_count,...,r_subjectivity,rouge-1_f,rouge-1_p,rouge-1_r,rouge-2_f,rouge-2_p,rouge-2_r,rouge-l_f,rouge-l_p,rouge-l_r
0,0,0,1135787,distance erie buffalo new york,erie canal distance table erie canal longest c...,0,7,41,5.0,58,...,0.443939,0.270270,0.156250,1.0,0.046512,0.025641,0.25,0.127565,0.125000,0.8
1,1,1,1135787,distance erie buffalo new york,distance erie buffalo distance erie buffalo st...,1,7,41,5.0,54,...,0.397222,0.222222,0.136364,0.6,0.133333,0.076923,0.50,0.141743,0.136364,0.6
2,2,2,1135787,distance erie buffalo new york,distance erie buffalo straight line 87 mile 13...,2,7,41,5.0,45,...,0.397222,0.222222,0.136364,0.6,0.137931,0.080000,0.50,0.141743,0.136364,0.6
3,3,3,1135787,distance erie buffalo new york,erie canal distance erie canal distance table ...,3,7,41,5.0,82,...,0.462626,0.232558,0.131579,1.0,0.075472,0.040816,0.50,0.106842,0.105263,0.8
4,4,4,1135787,distance erie buffalo new york,erie metropolitan area consists approximately ...,4,7,41,5.0,63,...,0.475455,0.177778,0.100000,0.8,0.083333,0.045455,0.50,0.101365,0.100000,0.8

In [20]:
tdata.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'queryID', 'query', 'response', 'labelID',
       'q_word_count', 'q_char_count', 'q_avg_word', 'r_word_count',
       'r_char_count', 'r_avg_word', 'q_polarity', 'q_subjectivity',
       'r_polarity', 'r_subjectivity', 'rouge-1_f', 'rouge-1_p', 'rouge-1_r',
       'rouge-2_f', 'rouge-2_p', 'rouge-2_r', 'rouge-l_f', 'rouge-l_p',
       'rouge-l_r'],
      dtype='object')

In [24]:
pred  = tdata.iloc[:,[16,17,18,19,20,21,22,23,24]].copy(deep=True)
pred.head()

,rouge-1_f,rouge-1_p,rouge-1_r,rouge-2_f,rouge-2_p,rouge-2_r,rouge-l_f,rouge-l_p,rouge-l_r
0,0.270270,0.156250,1.0,0.046512,0.025641,0.25,0.127565,0.125000,0.8
1,0.222222,0.136364,0.6,0.133333,0.076923,0.50,0.141743,0.136364,0.6
2,0.222222,0.136364,0.6,0.137931,0.080000,0.50,0.141743,0.136364,0.6
3,0.232558,0.131579,1.0,0.075472,0.040816,0.50,0.106842,0.105263,0.8
4,0.177778,0.100000,0.8,0.083333,0.045455,0.50,0.101365,0.100000,0.8

In [25]:
pred.sum(axis=1)

0         2.801238
1         2.546949
2         2.554624
3         2.992530
4         2.707930
5         2.367367
6         0.803772
7         1.096891
8         1.608638
9         2.546949
10        1.107219
11        0.691965
12        1.812679
13        1.441805
14        0.526923
15        0.841338
16        0.534882
17        0.874008
18        0.543535
19        0.495085
20        2.355335
21        0.000000
22        3.292842
23        0.000000
24        1.689701
25        2.606721
26        2.359223
27        2.467718
28        2.401449
29        2.545885
            ...
104140    0.000090
104141    0.000090
104142    0.000090
104143    0.000090
104144    0.000090
104145    0.000090
104146    0.000090
104147    0.000090
104148    0.000090
104149    0.000090
104150    0.000090
104151    0.000090
104152    0.000090
104153    0.000090
104154    0.000090
104155    0.000090
104156    0.000090
104157    0.000090
104158    0.000090
104159    0.000090
104160    0.000090
104161    0.000090
104162    0.000090
104163    0.000090
104164    0.000090
104165    0.000090
104166    0.000090
104167    0.000090
104168    0.000090
104169    0.000090
Length: 104170, dtype: float64

In [27]:
p = []
for i in range(0,tdata.shape[0],10):
    l = []
    v = pred[i:i+10].T
    l.append(tdata['queryID'][i])
    l.extend(v)
    p.append(l)

In [28]:
result = pd.DataFrame(p)

In [29]:
result.to_csv("answer.tsv",sep='\t',header=None,index=False)